### ISSUE TITLE
It stops working on facebook page from time to time

### ISSUE THREAD

**Issue by LatinSuD** [igrigorik/videospeed#1132]
Example:
https://www.facebook.com/reel/420174524346370

Error message is:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'div')
    at eval (eval at runAction (inject.js:771:13), <anonymous>:1:41)
    at Array.forEach (<anonymous>)
    at eval (eval at runAction (inject.js:771:13), <anonymous>:1:11)
    at runAction (inject.js:771:13)
    at HTMLDocument.<anonymous> (inject.js:611:11)
```

The problem is at line 771:

```
mediaTags.forEach(function (v) {
    var controller = v.vsc.div; 
    ...

```
In my case it was produce because of an AUDIO tag did not have a "vsc" attribute.
If I disable the "work on audio" extension option it works.

You could check for the attributes or simply use a try/catch block.

**Comment by LatinSuD** [comment]
Edit. It happens from time time.
I think it can happen even if audio tag is not enabled in settings.

**Comment by LatinSuD** [comment]
Update: It happens on video too from time to time.
I fixed the code locally (with a try/catch), I'll do a pull request later.

**Comment by LatinSuD** [comment]
Nevermind, I see it's been fixed in master branch. I see the code has been moved to `src/core/action-handler.js` and the `undefined` reference has been handled.

Chrome Store version is still having the issue, though.
